from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class AuthMePasswordPutRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, current_password=None, new_password=None):  # noqa: E501
        """AuthMePasswordPutRequest - a model defined in OpenAPI

        :param current_password: The current_password of this AuthMePasswordPutRequest.  # noqa: E501
        :type current_password: str
        :param new_password: The new_password of this AuthMePasswordPutRequest.  # noqa: E501
        :type new_password: str
        """
        self.openapi_types = {
            'current_password': str,
            'new_password': str
        }

        self.attribute_map = {
            'current_password': 'current_password',
            'new_password': 'new_password'
        }

        self._current_password = current_password
        self._new_password = new_password

    @classmethod
    def from_dict(cls, dikt) -> 'AuthMePasswordPutRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _auth_me_password_put_request of this AuthMePasswordPutRequest.  # noqa: E501
        :rtype: AuthMePasswordPutRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def current_password(self) -> str:
        """Gets the current_password of this AuthMePasswordPutRequest.


        :return: The current_password of this AuthMePasswordPutRequest.
        :rtype: str
        """
        return self._current_password

    @current_password.setter
    def current_password(self, current_password: str):
        """Sets the current_password of this AuthMePasswordPutRequest.


        :param current_password: The current_password of this AuthMePasswordPutRequest.
        :type current_password: str
        """
        if current_password is None:
            raise ValueError("Invalid value for `current_password`, must not be `None`")  # noqa: E501

        self._current_password = current_password

    @property
    def new_password(self) -> str:
        """Gets the new_password of this AuthMePasswordPutRequest.


        :return: The new_password of this AuthMePasswordPutRequest.
        :rtype: str
        """
        return self._new_password

    @new_password.setter
    def new_password(self, new_password: str):
        """Sets the new_password of this AuthMePasswordPutRequest.


        :param new_password: The new_password of this AuthMePasswordPutRequest.
        :type new_password: str
        """
        if new_password is None:
            raise ValueError("Invalid value for `new_password`, must not be `None`")  # noqa: E501
        if new_password is not None and len(new_password) < 8:
            raise ValueError("Invalid value for `new_password`, length must be greater than or equal to `8`")  # noqa: E501

        self._new_password = new_password
