from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class DocumentsIdPatchRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, public=None):  # noqa: E501
        """DocumentsIdPatchRequest - a model defined in OpenAPI

        :param public: The public of this DocumentsIdPatchRequest.  # noqa: E501
        :type public: bool
        """
        self.openapi_types = {
            'public': bool
        }

        self.attribute_map = {
            'public': 'public'
        }

        self._public = public

    @classmethod
    def from_dict(cls, dikt) -> 'DocumentsIdPatchRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _documents__id__patch_request of this DocumentsIdPatchRequest.  # noqa: E501
        :rtype: DocumentsIdPatchRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def public(self) -> bool:
        """Gets the public of this DocumentsIdPatchRequest.

        Set to true to release this document publicly.  # noqa: E501

        :return: The public of this DocumentsIdPatchRequest.
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public: bool):
        """Sets the public of this DocumentsIdPatchRequest.

        Set to true to release this document publicly.  # noqa: E501

        :param public: The public of this DocumentsIdPatchRequest.
        :type public: bool
        """

        self._public = public
