from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Document(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, filename=None, type=None, status=None, public=None, owner_ids=None, entity_count=None, created_at=None, error_message=None):  # noqa: E501
        """Document - a model defined in OpenAPI

        :param id: The id of this Document.  # noqa: E501
        :type id: str
        :param filename: The filename of this Document.  # noqa: E501
        :type filename: str
        :param type: The type of this Document.  # noqa: E501
        :type type: str
        :param status: The status of this Document.  # noqa: E501
        :type status: str
        :param public: The public of this Document.  # noqa: E501
        :type public: bool
        :param owner_ids: The owner_ids of this Document.  # noqa: E501
        :type owner_ids: List[str]
        :param entity_count: The entity_count of this Document.  # noqa: E501
        :type entity_count: int
        :param created_at: The created_at of this Document.  # noqa: E501
        :type created_at: datetime
        :param error_message: The error_message of this Document.  # noqa: E501
        :type error_message: str
        """
        self.openapi_types = {
            'id': str,
            'filename': str,
            'type': str,
            'status': str,
            'public': bool,
            'owner_ids': List[str],
            'entity_count': int,
            'created_at': datetime,
            'error_message': str
        }

        self.attribute_map = {
            'id': 'id',
            'filename': 'filename',
            'type': 'type',
            'status': 'status',
            'public': 'public',
            'owner_ids': 'owner_ids',
            'entity_count': 'entity_count',
            'created_at': 'created_at',
            'error_message': 'error_message'
        }

        self._id = id
        self._filename = filename
        self._type = type
        self._status = status
        self._public = public
        self._owner_ids = owner_ids
        self._entity_count = entity_count
        self._created_at = created_at
        self._error_message = error_message

    @classmethod
    def from_dict(cls, dikt) -> 'Document':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Document of this Document.  # noqa: E501
        :rtype: Document
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Document.


        :return: The id of this Document.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Document.


        :param id: The id of this Document.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def filename(self) -> str:
        """Gets the filename of this Document.


        :return: The filename of this Document.
        :rtype: str
        """
        return self._filename

    @filename.setter
    def filename(self, filename: str):
        """Sets the filename of this Document.


        :param filename: The filename of this Document.
        :type filename: str
        """
        if filename is None:
            raise ValueError("Invalid value for `filename`, must not be `None`")  # noqa: E501

        self._filename = filename

    @property
    def type(self) -> str:
        """Gets the type of this Document.


        :return: The type of this Document.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this Document.


        :param type: The type of this Document.
        :type type: str
        """
        allowed_values = ["text", "pdf"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def status(self) -> str:
        """Gets the status of this Document.


        :return: The status of this Document.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this Document.


        :param status: The status of this Document.
        :type status: str
        """
        allowed_values = ["queued", "ocr_processing", "ner_processing", "completed", "failed"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def public(self) -> bool:
        """Gets the public of this Document.

        True if one or more owners have released this document publicly. Any owner may set this to true. Once public it can only be reversed by all owners agreeing (business logic, not enforced here).   # noqa: E501

        :return: The public of this Document.
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public: bool):
        """Sets the public of this Document.

        True if one or more owners have released this document publicly. Any owner may set this to true. Once public it can only be reversed by all owners agreeing (business logic, not enforced here).   # noqa: E501

        :param public: The public of this Document.
        :type public: bool
        """
        if public is None:
            raise ValueError("Invalid value for `public`, must not be `None`")  # noqa: E501

        self._public = public

    @property
    def owner_ids(self) -> List[str]:
        """Gets the owner_ids of this Document.

        IDs of all users who have uploaded this document.  # noqa: E501

        :return: The owner_ids of this Document.
        :rtype: List[str]
        """
        return self._owner_ids

    @owner_ids.setter
    def owner_ids(self, owner_ids: List[str]):
        """Sets the owner_ids of this Document.

        IDs of all users who have uploaded this document.  # noqa: E501

        :param owner_ids: The owner_ids of this Document.
        :type owner_ids: List[str]
        """
        if owner_ids is None:
            raise ValueError("Invalid value for `owner_ids`, must not be `None`")  # noqa: E501

        self._owner_ids = owner_ids

    @property
    def entity_count(self) -> int:
        """Gets the entity_count of this Document.

        Number of FtM entities extracted from this document.  # noqa: E501

        :return: The entity_count of this Document.
        :rtype: int
        """
        return self._entity_count

    @entity_count.setter
    def entity_count(self, entity_count: int):
        """Sets the entity_count of this Document.

        Number of FtM entities extracted from this document.  # noqa: E501

        :param entity_count: The entity_count of this Document.
        :type entity_count: int
        """

        self._entity_count = entity_count

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Document.


        :return: The created_at of this Document.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Document.


        :param created_at: The created_at of this Document.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def error_message(self) -> str:
        """Gets the error_message of this Document.

        Present when status=failed.  # noqa: E501

        :return: The error_message of this Document.
        :rtype: str
        """
        return self._error_message

    @error_message.setter
    def error_message(self, error_message: str):
        """Sets the error_message of this Document.

        Present when status=failed.  # noqa: E501

        :param error_message: The error_message of this Document.
        :type error_message: str
        """

        self._error_message = error_message
