from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.document import Document
from openapi_server import util

from openapi_server.models.document import Document  # noqa: E501

class DocumentListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total=None, page=None, page_size=None, results=None):  # noqa: E501
        """DocumentListResponse - a model defined in OpenAPI

        :param total: The total of this DocumentListResponse.  # noqa: E501
        :type total: int
        :param page: The page of this DocumentListResponse.  # noqa: E501
        :type page: int
        :param page_size: The page_size of this DocumentListResponse.  # noqa: E501
        :type page_size: int
        :param results: The results of this DocumentListResponse.  # noqa: E501
        :type results: List[Document]
        """
        self.openapi_types = {
            'total': int,
            'page': int,
            'page_size': int,
            'results': List[Document]
        }

        self.attribute_map = {
            'total': 'total',
            'page': 'page',
            'page_size': 'page_size',
            'results': 'results'
        }

        self._total = total
        self._page = page
        self._page_size = page_size
        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'DocumentListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DocumentListResponse of this DocumentListResponse.  # noqa: E501
        :rtype: DocumentListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this DocumentListResponse.


        :return: The total of this DocumentListResponse.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this DocumentListResponse.


        :param total: The total of this DocumentListResponse.
        :type total: int
        """

        self._total = total

    @property
    def page(self) -> int:
        """Gets the page of this DocumentListResponse.


        :return: The page of this DocumentListResponse.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page: int):
        """Sets the page of this DocumentListResponse.


        :param page: The page of this DocumentListResponse.
        :type page: int
        """

        self._page = page

    @property
    def page_size(self) -> int:
        """Gets the page_size of this DocumentListResponse.


        :return: The page_size of this DocumentListResponse.
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size: int):
        """Sets the page_size of this DocumentListResponse.


        :param page_size: The page_size of this DocumentListResponse.
        :type page_size: int
        """

        self._page_size = page_size

    @property
    def results(self) -> List[Document]:
        """Gets the results of this DocumentListResponse.


        :return: The results of this DocumentListResponse.
        :rtype: List[Document]
        """
        return self._results

    @results.setter
    def results(self, results: List[Document]):
        """Sets the results of this DocumentListResponse.


        :param results: The results of this DocumentListResponse.
        :type results: List[Document]
        """

        self._results = results
