from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.provenance_entry import ProvenanceEntry
from openapi_server import util

from openapi_server.models.provenance_entry import ProvenanceEntry  # noqa: E501

class FtMEntity(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, _schema=None, caption=None, properties=None, confidence=None, public=False, owner_ids=None, provenance=None, first_seen=None, last_changed=None):  # noqa: E501
        """FtMEntity - a model defined in OpenAPI

        :param id: The id of this FtMEntity.  # noqa: E501
        :type id: str
        :param _schema: The _schema of this FtMEntity.  # noqa: E501
        :type _schema: str
        :param caption: The caption of this FtMEntity.  # noqa: E501
        :type caption: str
        :param properties: The properties of this FtMEntity.  # noqa: E501
        :type properties: Dict[str, List[str]]
        :param confidence: The confidence of this FtMEntity.  # noqa: E501
        :type confidence: float
        :param public: The public of this FtMEntity.  # noqa: E501
        :type public: bool
        :param owner_ids: The owner_ids of this FtMEntity.  # noqa: E501
        :type owner_ids: List[str]
        :param provenance: The provenance of this FtMEntity.  # noqa: E501
        :type provenance: List[ProvenanceEntry]
        :param first_seen: The first_seen of this FtMEntity.  # noqa: E501
        :type first_seen: datetime
        :param last_changed: The last_changed of this FtMEntity.  # noqa: E501
        :type last_changed: datetime
        """
        self.openapi_types = {
            'id': str,
            '_schema': str,
            'caption': str,
            'properties': Dict[str, List[str]],
            'confidence': float,
            'public': bool,
            'owner_ids': List[str],
            'provenance': List[ProvenanceEntry],
            'first_seen': datetime,
            'last_changed': datetime
        }

        self.attribute_map = {
            'id': 'id',
            '_schema': 'schema',
            'caption': 'caption',
            'properties': 'properties',
            'confidence': 'confidence',
            'public': 'public',
            'owner_ids': 'owner_ids',
            'provenance': 'provenance',
            'first_seen': 'first_seen',
            'last_changed': 'last_changed'
        }

        self._id = id
        self.__schema = _schema
        self._caption = caption
        self._properties = properties
        self._confidence = confidence
        self._public = public
        self._owner_ids = owner_ids
        self._provenance = provenance
        self._first_seen = first_seen
        self._last_changed = last_changed

    @classmethod
    def from_dict(cls, dikt) -> 'FtMEntity':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FtMEntity of this FtMEntity.  # noqa: E501
        :rtype: FtMEntity
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this FtMEntity.

        Stable unique identifier (hash of canonical values).  # noqa: E501

        :return: The id of this FtMEntity.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this FtMEntity.

        Stable unique identifier (hash of canonical values).  # noqa: E501

        :param id: The id of this FtMEntity.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def _schema(self) -> str:
        """Gets the _schema of this FtMEntity.

        FtM core schema type. Node-like examples: Person, Organization, Company, LegalEntity, Asset, Vehicle, Vessel, Aircraft, Address, Passport, BankAccount. Edge-like examples: Ownership, Membership, Directorship, Family, Associate, UnknownLink, Sanction, Payment. This is not an exhaustive list; any valid FtM core schema is accepted.   # noqa: E501

        :return: The _schema of this FtMEntity.
        :rtype: str
        """
        return self.__schema

    @_schema.setter
    def _schema(self, _schema: str):
        """Sets the _schema of this FtMEntity.

        FtM core schema type. Node-like examples: Person, Organization, Company, LegalEntity, Asset, Vehicle, Vessel, Aircraft, Address, Passport, BankAccount. Edge-like examples: Ownership, Membership, Directorship, Family, Associate, UnknownLink, Sanction, Payment. This is not an exhaustive list; any valid FtM core schema is accepted.   # noqa: E501

        :param _schema: The _schema of this FtMEntity.
        :type _schema: str
        """
        if _schema is None:
            raise ValueError("Invalid value for `_schema`, must not be `None`")  # noqa: E501

        self.__schema = _schema

    @property
    def caption(self) -> str:
        """Gets the caption of this FtMEntity.

        Human-readable label computed from featured properties (e.g. name). Read-only; computed by the backend.   # noqa: E501

        :return: The caption of this FtMEntity.
        :rtype: str
        """
        return self._caption

    @caption.setter
    def caption(self, caption: str):
        """Sets the caption of this FtMEntity.

        Human-readable label computed from featured properties (e.g. name). Read-only; computed by the backend.   # noqa: E501

        :param caption: The caption of this FtMEntity.
        :type caption: str
        """

        self._caption = caption

    @property
    def properties(self) -> Dict[str, List[str]]:
        """Gets the properties of this FtMEntity.

        Multi-valued property bag. ALL values are arrays of strings, even scalar-feeling fields like name or birthDate. Property names are defined by the FtM schema for this entity type. Entity-typed properties (e.g. Ownership.owner) hold the IDs of other entities.   # noqa: E501

        :return: The properties of this FtMEntity.
        :rtype: Dict[str, List[str]]
        """
        return self._properties

    @properties.setter
    def properties(self, properties: Dict[str, List[str]]):
        """Sets the properties of this FtMEntity.

        Multi-valued property bag. ALL values are arrays of strings, even scalar-feeling fields like name or birthDate. Property names are defined by the FtM schema for this entity type. Entity-typed properties (e.g. Ownership.owner) hold the IDs of other entities.   # noqa: E501

        :param properties: The properties of this FtMEntity.
        :type properties: Dict[str, List[str]]
        """
        if properties is None:
            raise ValueError("Invalid value for `properties`, must not be `None`")  # noqa: E501

        self._properties = properties

    @property
    def confidence(self) -> float:
        """Gets the confidence of this FtMEntity.

        NER confidence score assigned by the ner_service. Stored for all entities regardless of value. Null only for manually created entities.   # noqa: E501

        :return: The confidence of this FtMEntity.
        :rtype: float
        """
        return self._confidence

    @confidence.setter
    def confidence(self, confidence: float):
        """Sets the confidence of this FtMEntity.

        NER confidence score assigned by the ner_service. Stored for all entities regardless of value. Null only for manually created entities.   # noqa: E501

        :param confidence: The confidence of this FtMEntity.
        :type confidence: float
        """
        if confidence is not None and confidence > 1.0:  # noqa: E501
            raise ValueError("Invalid value for `confidence`, must be a value less than or equal to `1.0`")  # noqa: E501
        if confidence is not None and confidence < 0.0:  # noqa: E501
            raise ValueError("Invalid value for `confidence`, must be a value greater than or equal to `0.0`")  # noqa: E501

        self._confidence = confidence

    @property
    def public(self) -> bool:
        """Gets the public of this FtMEntity.

        True if any owning user has released this entity publicly. Derived from the public flags of all documents it was sourced from.   # noqa: E501

        :return: The public of this FtMEntity.
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public: bool):
        """Sets the public of this FtMEntity.

        True if any owning user has released this entity publicly. Derived from the public flags of all documents it was sourced from.   # noqa: E501

        :param public: The public of this FtMEntity.
        :type public: bool
        """

        self._public = public

    @property
    def owner_ids(self) -> List[str]:
        """Gets the owner_ids of this FtMEntity.

        User IDs who own at least one source document for this entity.  # noqa: E501

        :return: The owner_ids of this FtMEntity.
        :rtype: List[str]
        """
        return self._owner_ids

    @owner_ids.setter
    def owner_ids(self, owner_ids: List[str]):
        """Sets the owner_ids of this FtMEntity.

        User IDs who own at least one source document for this entity.  # noqa: E501

        :param owner_ids: The owner_ids of this FtMEntity.
        :type owner_ids: List[str]
        """

        self._owner_ids = owner_ids

    @property
    def provenance(self) -> List[ProvenanceEntry]:
        """Gets the provenance of this FtMEntity.

        All document+page references that contributed to this entity. An entity sourced from multiple documents will have multiple provenance entries.   # noqa: E501

        :return: The provenance of this FtMEntity.
        :rtype: List[ProvenanceEntry]
        """
        return self._provenance

    @provenance.setter
    def provenance(self, provenance: List[ProvenanceEntry]):
        """Sets the provenance of this FtMEntity.

        All document+page references that contributed to this entity. An entity sourced from multiple documents will have multiple provenance entries.   # noqa: E501

        :param provenance: The provenance of this FtMEntity.
        :type provenance: List[ProvenanceEntry]
        """

        self._provenance = provenance

    @property
    def first_seen(self) -> datetime:
        """Gets the first_seen of this FtMEntity.


        :return: The first_seen of this FtMEntity.
        :rtype: datetime
        """
        return self._first_seen

    @first_seen.setter
    def first_seen(self, first_seen: datetime):
        """Sets the first_seen of this FtMEntity.


        :param first_seen: The first_seen of this FtMEntity.
        :type first_seen: datetime
        """

        self._first_seen = first_seen

    @property
    def last_changed(self) -> datetime:
        """Gets the last_changed of this FtMEntity.


        :return: The last_changed of this FtMEntity.
        :rtype: datetime
        """
        return self._last_changed

    @last_changed.setter
    def last_changed(self, last_changed: datetime):
        """Sets the last_changed of this FtMEntity.


        :param last_changed: The last_changed of this FtMEntity.
        :type last_changed: datetime
        """

        self._last_changed = last_changed
