from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class JobStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, job_id=None, document_id=None, status=None, progress=None, message=None, created_at=None, updated_at=None):  # noqa: E501
        """JobStatus - a model defined in OpenAPI

        :param job_id: The job_id of this JobStatus.  # noqa: E501
        :type job_id: str
        :param document_id: The document_id of this JobStatus.  # noqa: E501
        :type document_id: str
        :param status: The status of this JobStatus.  # noqa: E501
        :type status: str
        :param progress: The progress of this JobStatus.  # noqa: E501
        :type progress: int
        :param message: The message of this JobStatus.  # noqa: E501
        :type message: str
        :param created_at: The created_at of this JobStatus.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this JobStatus.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'job_id': str,
            'document_id': str,
            'status': str,
            'progress': int,
            'message': str,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'job_id': 'job_id',
            'document_id': 'document_id',
            'status': 'status',
            'progress': 'progress',
            'message': 'message',
            'created_at': 'created_at',
            'updated_at': 'updated_at'
        }

        self._job_id = job_id
        self._document_id = document_id
        self._status = status
        self._progress = progress
        self._message = message
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'JobStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The JobStatus of this JobStatus.  # noqa: E501
        :rtype: JobStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def job_id(self) -> str:
        """Gets the job_id of this JobStatus.


        :return: The job_id of this JobStatus.
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id: str):
        """Sets the job_id of this JobStatus.


        :param job_id: The job_id of this JobStatus.
        :type job_id: str
        """
        if job_id is None:
            raise ValueError("Invalid value for `job_id`, must not be `None`")  # noqa: E501

        self._job_id = job_id

    @property
    def document_id(self) -> str:
        """Gets the document_id of this JobStatus.

        ID of the Document record created for this job.  # noqa: E501

        :return: The document_id of this JobStatus.
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id: str):
        """Sets the document_id of this JobStatus.

        ID of the Document record created for this job.  # noqa: E501

        :param document_id: The document_id of this JobStatus.
        :type document_id: str
        """

        self._document_id = document_id

    @property
    def status(self) -> str:
        """Gets the status of this JobStatus.


        :return: The status of this JobStatus.
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status: str):
        """Sets the status of this JobStatus.


        :param status: The status of this JobStatus.
        :type status: str
        """
        allowed_values = ["queued", "ocr_processing", "ner_processing", "completed", "failed"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def progress(self) -> int:
        """Gets the progress of this JobStatus.

        Estimated completion percentage.  # noqa: E501

        :return: The progress of this JobStatus.
        :rtype: int
        """
        return self._progress

    @progress.setter
    def progress(self, progress: int):
        """Sets the progress of this JobStatus.

        Estimated completion percentage.  # noqa: E501

        :param progress: The progress of this JobStatus.
        :type progress: int
        """
        if progress is not None and progress > 100:  # noqa: E501
            raise ValueError("Invalid value for `progress`, must be a value less than or equal to `100`")  # noqa: E501
        if progress is not None and progress < 0:  # noqa: E501
            raise ValueError("Invalid value for `progress`, must be a value greater than or equal to `0`")  # noqa: E501

        self._progress = progress

    @property
    def message(self) -> str:
        """Gets the message of this JobStatus.

        Human-readable status detail or error message.  # noqa: E501

        :return: The message of this JobStatus.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this JobStatus.

        Human-readable status detail or error message.  # noqa: E501

        :param message: The message of this JobStatus.
        :type message: str
        """

        self._message = message

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this JobStatus.


        :return: The created_at of this JobStatus.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this JobStatus.


        :param created_at: The created_at of this JobStatus.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this JobStatus.


        :return: The updated_at of this JobStatus.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this JobStatus.


        :param updated_at: The updated_at of this JobStatus.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
