from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.job_status import JobStatus
from openapi_server import util

from openapi_server.models.job_status import JobStatus  # noqa: E501

class JobsGet200Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total=None, results=None):  # noqa: E501
        """JobsGet200Response - a model defined in OpenAPI

        :param total: The total of this JobsGet200Response.  # noqa: E501
        :type total: int
        :param results: The results of this JobsGet200Response.  # noqa: E501
        :type results: List[JobStatus]
        """
        self.openapi_types = {
            'total': int,
            'results': List[JobStatus]
        }

        self.attribute_map = {
            'total': 'total',
            'results': 'results'
        }

        self._total = total
        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'JobsGet200Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _jobs_get_200_response of this JobsGet200Response.  # noqa: E501
        :rtype: JobsGet200Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this JobsGet200Response.


        :return: The total of this JobsGet200Response.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this JobsGet200Response.


        :param total: The total of this JobsGet200Response.
        :type total: int
        """

        self._total = total

    @property
    def results(self) -> List[JobStatus]:
        """Gets the results of this JobsGet200Response.


        :return: The results of this JobsGet200Response.
        :rtype: List[JobStatus]
        """
        return self._results

    @results.setter
    def results(self, results: List[JobStatus]):
        """Sets the results of this JobsGet200Response.


        :param results: The results of this JobsGet200Response.
        :type results: List[JobStatus]
        """

        self._results = results
