from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.ner_input_page import NerInputPage
from openapi_server import util

from openapi_server.models.ner_input_page import NerInputPage  # noqa: E501

class NerRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, document_id=None, pages=None):  # noqa: E501
        """NerRequest - a model defined in OpenAPI

        :param document_id: The document_id of this NerRequest.  # noqa: E501
        :type document_id: str
        :param pages: The pages of this NerRequest.  # noqa: E501
        :type pages: List[NerInputPage]
        """
        self.openapi_types = {
            'document_id': str,
            'pages': List[NerInputPage]
        }

        self.attribute_map = {
            'document_id': 'document_id',
            'pages': 'pages'
        }

        self._document_id = document_id
        self._pages = pages

    @classmethod
    def from_dict(cls, dikt) -> 'NerRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NerRequest of this NerRequest.  # noqa: E501
        :rtype: NerRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def document_id(self) -> str:
        """Gets the document_id of this NerRequest.


        :return: The document_id of this NerRequest.
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id: str):
        """Sets the document_id of this NerRequest.


        :param document_id: The document_id of this NerRequest.
        :type document_id: str
        """
        if document_id is None:
            raise ValueError("Invalid value for `document_id`, must not be `None`")  # noqa: E501

        self._document_id = document_id

    @property
    def pages(self) -> List[NerInputPage]:
        """Gets the pages of this NerRequest.

        Pages of text to analyse. For plain-text documents, send a single entry with page_number=null.   # noqa: E501

        :return: The pages of this NerRequest.
        :rtype: List[NerInputPage]
        """
        return self._pages

    @pages.setter
    def pages(self, pages: List[NerInputPage]):
        """Sets the pages of this NerRequest.

        Pages of text to analyse. For plain-text documents, send a single entry with page_number=null.   # noqa: E501

        :param pages: The pages of this NerRequest.
        :type pages: List[NerInputPage]
        """
        if pages is None:
            raise ValueError("Invalid value for `pages`, must not be `None`")  # noqa: E501

        self._pages = pages
