from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class OcrRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, document_id=None, file_base64=None, mime_type=None):  # noqa: E501
        """OcrRequest - a model defined in OpenAPI

        :param document_id: The document_id of this OcrRequest.  # noqa: E501
        :type document_id: str
        :param file_base64: The file_base64 of this OcrRequest.  # noqa: E501
        :type file_base64: str
        :param mime_type: The mime_type of this OcrRequest.  # noqa: E501
        :type mime_type: str
        """
        self.openapi_types = {
            'document_id': str,
            'file_base64': str,
            'mime_type': str
        }

        self.attribute_map = {
            'document_id': 'document_id',
            'file_base64': 'file_base64',
            'mime_type': 'mime_type'
        }

        self._document_id = document_id
        self._file_base64 = file_base64
        self._mime_type = mime_type

    @classmethod
    def from_dict(cls, dikt) -> 'OcrRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OcrRequest of this OcrRequest.  # noqa: E501
        :rtype: OcrRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def document_id(self) -> str:
        """Gets the document_id of this OcrRequest.


        :return: The document_id of this OcrRequest.
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id: str):
        """Sets the document_id of this OcrRequest.


        :param document_id: The document_id of this OcrRequest.
        :type document_id: str
        """
        if document_id is None:
            raise ValueError("Invalid value for `document_id`, must not be `None`")  # noqa: E501

        self._document_id = document_id

    @property
    def file_base64(self) -> str:
        """Gets the file_base64 of this OcrRequest.

        Base64-encoded PDF binary.  # noqa: E501

        :return: The file_base64 of this OcrRequest.
        :rtype: str
        """
        return self._file_base64

    @file_base64.setter
    def file_base64(self, file_base64: str):
        """Sets the file_base64 of this OcrRequest.

        Base64-encoded PDF binary.  # noqa: E501

        :param file_base64: The file_base64 of this OcrRequest.
        :type file_base64: str
        """
        if file_base64 is None:
            raise ValueError("Invalid value for `file_base64`, must not be `None`")  # noqa: E501

        self._file_base64 = file_base64

    @property
    def mime_type(self) -> str:
        """Gets the mime_type of this OcrRequest.


        :return: The mime_type of this OcrRequest.
        :rtype: str
        """
        return self._mime_type

    @mime_type.setter
    def mime_type(self, mime_type: str):
        """Sets the mime_type of this OcrRequest.


        :param mime_type: The mime_type of this OcrRequest.
        :type mime_type: str
        """
        allowed_values = ["application/pdf"]  # noqa: E501
        if mime_type not in allowed_values:
            raise ValueError(
                "Invalid value for `mime_type` ({0}), must be one of {1}"
                .format(mime_type, allowed_values)
            )

        self._mime_type = mime_type
