from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class OcrPage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, page_number=None, text=None):  # noqa: E501
        """OcrPage - a model defined in OpenAPI

        :param page_number: The page_number of this OcrPage.  # noqa: E501
        :type page_number: int
        :param text: The text of this OcrPage.  # noqa: E501
        :type text: str
        """
        self.openapi_types = {
            'page_number': int,
            'text': str
        }

        self.attribute_map = {
            'page_number': 'page_number',
            'text': 'text'
        }

        self._page_number = page_number
        self._text = text

    @classmethod
    def from_dict(cls, dikt) -> 'OcrPage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OcrPage of this OcrPage.  # noqa: E501
        :rtype: OcrPage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def page_number(self) -> int:
        """Gets the page_number of this OcrPage.


        :return: The page_number of this OcrPage.
        :rtype: int
        """
        return self._page_number

    @page_number.setter
    def page_number(self, page_number: int):
        """Sets the page_number of this OcrPage.


        :param page_number: The page_number of this OcrPage.
        :type page_number: int
        """
        if page_number is None:
            raise ValueError("Invalid value for `page_number`, must not be `None`")  # noqa: E501
        if page_number is not None and page_number < 1:  # noqa: E501
            raise ValueError("Invalid value for `page_number`, must be a value greater than or equal to `1`")  # noqa: E501

        self._page_number = page_number

    @property
    def text(self) -> str:
        """Gets the text of this OcrPage.


        :return: The text of this OcrPage.
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text: str):
        """Sets the text of this OcrPage.


        :param text: The text of this OcrPage.
        :type text: str
        """
        if text is None:
            raise ValueError("Invalid value for `text`, must not be `None`")  # noqa: E501

        self._text = text
