from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.project import Project
from openapi_server import util

from openapi_server.models.project import Project  # noqa: E501

class ProjectListResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, total=None, results=None):  # noqa: E501
        """ProjectListResponse - a model defined in OpenAPI

        :param total: The total of this ProjectListResponse.  # noqa: E501
        :type total: int
        :param results: The results of this ProjectListResponse.  # noqa: E501
        :type results: List[Project]
        """
        self.openapi_types = {
            'total': int,
            'results': List[Project]
        }

        self.attribute_map = {
            'total': 'total',
            'results': 'results'
        }

        self._total = total
        self._results = results

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectListResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProjectListResponse of this ProjectListResponse.  # noqa: E501
        :rtype: ProjectListResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def total(self) -> int:
        """Gets the total of this ProjectListResponse.


        :return: The total of this ProjectListResponse.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total: int):
        """Sets the total of this ProjectListResponse.


        :param total: The total of this ProjectListResponse.
        :type total: int
        """

        self._total = total

    @property
    def results(self) -> List[Project]:
        """Gets the results of this ProjectListResponse.


        :return: The results of this ProjectListResponse.
        :rtype: List[Project]
        """
        return self._results

    @results.setter
    def results(self, results: List[Project]):
        """Sets the results of this ProjectListResponse.


        :param results: The results of this ProjectListResponse.
        :type results: List[Project]
        """

        self._results = results
