from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.project_snapshot import ProjectSnapshot
from openapi_server import util

from openapi_server.models.project_snapshot import ProjectSnapshot  # noqa: E501

class ProjectsIdPutRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, description=None, snapshot=None):  # noqa: E501
        """ProjectsIdPutRequest - a model defined in OpenAPI

        :param name: The name of this ProjectsIdPutRequest.  # noqa: E501
        :type name: str
        :param description: The description of this ProjectsIdPutRequest.  # noqa: E501
        :type description: str
        :param snapshot: The snapshot of this ProjectsIdPutRequest.  # noqa: E501
        :type snapshot: ProjectSnapshot
        """
        self.openapi_types = {
            'name': str,
            'description': str,
            'snapshot': ProjectSnapshot
        }

        self.attribute_map = {
            'name': 'name',
            'description': 'description',
            'snapshot': 'snapshot'
        }

        self._name = name
        self._description = description
        self._snapshot = snapshot

    @classmethod
    def from_dict(cls, dikt) -> 'ProjectsIdPutRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _projects__id__put_request of this ProjectsIdPutRequest.  # noqa: E501
        :rtype: ProjectsIdPutRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this ProjectsIdPutRequest.


        :return: The name of this ProjectsIdPutRequest.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this ProjectsIdPutRequest.


        :param name: The name of this ProjectsIdPutRequest.
        :type name: str
        """

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this ProjectsIdPutRequest.


        :return: The description of this ProjectsIdPutRequest.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this ProjectsIdPutRequest.


        :param description: The description of this ProjectsIdPutRequest.
        :type description: str
        """

        self._description = description

    @property
    def snapshot(self) -> ProjectSnapshot:
        """Gets the snapshot of this ProjectsIdPutRequest.


        :return: The snapshot of this ProjectsIdPutRequest.
        :rtype: ProjectSnapshot
        """
        return self._snapshot

    @snapshot.setter
    def snapshot(self, snapshot: ProjectSnapshot):
        """Sets the snapshot of this ProjectsIdPutRequest.


        :param snapshot: The snapshot of this ProjectsIdPutRequest.
        :type snapshot: ProjectSnapshot
        """

        self._snapshot = snapshot
