from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.project_snapshot import ProjectSnapshot
from openapi_server import util

from openapi_server.models.project_snapshot import ProjectSnapshot  # noqa: E501

class Project(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, description=None, owner_id=None, snapshot=None, created_at=None, updated_at=None):  # noqa: E501
        """Project - a model defined in OpenAPI

        :param id: The id of this Project.  # noqa: E501
        :type id: str
        :param name: The name of this Project.  # noqa: E501
        :type name: str
        :param description: The description of this Project.  # noqa: E501
        :type description: str
        :param owner_id: The owner_id of this Project.  # noqa: E501
        :type owner_id: str
        :param snapshot: The snapshot of this Project.  # noqa: E501
        :type snapshot: ProjectSnapshot
        :param created_at: The created_at of this Project.  # noqa: E501
        :type created_at: datetime
        :param updated_at: The updated_at of this Project.  # noqa: E501
        :type updated_at: datetime
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'description': str,
            'owner_id': str,
            'snapshot': ProjectSnapshot,
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'description': 'description',
            'owner_id': 'owner_id',
            'snapshot': 'snapshot',
            'created_at': 'created_at',
            'updated_at': 'updated_at'
        }

        self._id = id
        self._name = name
        self._description = description
        self._owner_id = owner_id
        self._snapshot = snapshot
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'Project':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Project of this Project.  # noqa: E501
        :rtype: Project
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Project.


        :return: The id of this Project.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Project.


        :param id: The id of this Project.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Project.


        :return: The name of this Project.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Project.


        :param name: The name of this Project.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def description(self) -> str:
        """Gets the description of this Project.


        :return: The description of this Project.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this Project.


        :param description: The description of this Project.
        :type description: str
        """

        self._description = description

    @property
    def owner_id(self) -> str:
        """Gets the owner_id of this Project.


        :return: The owner_id of this Project.
        :rtype: str
        """
        return self._owner_id

    @owner_id.setter
    def owner_id(self, owner_id: str):
        """Sets the owner_id of this Project.


        :param owner_id: The owner_id of this Project.
        :type owner_id: str
        """
        if owner_id is None:
            raise ValueError("Invalid value for `owner_id`, must not be `None`")  # noqa: E501

        self._owner_id = owner_id

    @property
    def snapshot(self) -> ProjectSnapshot:
        """Gets the snapshot of this Project.


        :return: The snapshot of this Project.
        :rtype: ProjectSnapshot
        """
        return self._snapshot

    @snapshot.setter
    def snapshot(self, snapshot: ProjectSnapshot):
        """Sets the snapshot of this Project.


        :param snapshot: The snapshot of this Project.
        :type snapshot: ProjectSnapshot
        """
        if snapshot is None:
            raise ValueError("Invalid value for `snapshot`, must not be `None`")  # noqa: E501

        self._snapshot = snapshot

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this Project.


        :return: The created_at of this Project.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this Project.


        :param created_at: The created_at of this Project.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this Project.


        :return: The updated_at of this Project.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this Project.


        :param updated_at: The updated_at of this Project.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
