from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ProvenanceEntry(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, document_id=None, page_number=None):  # noqa: E501
        """ProvenanceEntry - a model defined in OpenAPI

        :param document_id: The document_id of this ProvenanceEntry.  # noqa: E501
        :type document_id: str
        :param page_number: The page_number of this ProvenanceEntry.  # noqa: E501
        :type page_number: int
        """
        self.openapi_types = {
            'document_id': str,
            'page_number': int
        }

        self.attribute_map = {
            'document_id': 'document_id',
            'page_number': 'page_number'
        }

        self._document_id = document_id
        self._page_number = page_number

    @classmethod
    def from_dict(cls, dikt) -> 'ProvenanceEntry':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProvenanceEntry of this ProvenanceEntry.  # noqa: E501
        :rtype: ProvenanceEntry
        """
        return util.deserialize_model(dikt, cls)

    @property
    def document_id(self) -> str:
        """Gets the document_id of this ProvenanceEntry.


        :return: The document_id of this ProvenanceEntry.
        :rtype: str
        """
        return self._document_id

    @document_id.setter
    def document_id(self, document_id: str):
        """Sets the document_id of this ProvenanceEntry.


        :param document_id: The document_id of this ProvenanceEntry.
        :type document_id: str
        """
        if document_id is None:
            raise ValueError("Invalid value for `document_id`, must not be `None`")  # noqa: E501

        self._document_id = document_id

    @property
    def page_number(self) -> int:
        """Gets the page_number of this ProvenanceEntry.

        1-indexed page number. Null for plain-text documents.  # noqa: E501

        :return: The page_number of this ProvenanceEntry.
        :rtype: int
        """
        return self._page_number

    @page_number.setter
    def page_number(self, page_number: int):
        """Sets the page_number of this ProvenanceEntry.

        1-indexed page number. Null for plain-text documents.  # noqa: E501

        :param page_number: The page_number of this ProvenanceEntry.
        :type page_number: int
        """
        if page_number is not None and page_number < 1:  # noqa: E501
            raise ValueError("Invalid value for `page_number`, must be a value greater than or equal to `1`")  # noqa: E501

        self._page_number = page_number
