from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class RegisterRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, email=None, password=None, display_name=None):  # noqa: E501
        """RegisterRequest - a model defined in OpenAPI

        :param email: The email of this RegisterRequest.  # noqa: E501
        :type email: str
        :param password: The password of this RegisterRequest.  # noqa: E501
        :type password: str
        :param display_name: The display_name of this RegisterRequest.  # noqa: E501
        :type display_name: str
        """
        self.openapi_types = {
            'email': str,
            'password': str,
            'display_name': str
        }

        self.attribute_map = {
            'email': 'email',
            'password': 'password',
            'display_name': 'display_name'
        }

        self._email = email
        self._password = password
        self._display_name = display_name

    @classmethod
    def from_dict(cls, dikt) -> 'RegisterRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RegisterRequest of this RegisterRequest.  # noqa: E501
        :rtype: RegisterRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def email(self) -> str:
        """Gets the email of this RegisterRequest.


        :return: The email of this RegisterRequest.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this RegisterRequest.


        :param email: The email of this RegisterRequest.
        :type email: str
        """
        if email is None:
            raise ValueError("Invalid value for `email`, must not be `None`")  # noqa: E501

        self._email = email

    @property
    def password(self) -> str:
        """Gets the password of this RegisterRequest.


        :return: The password of this RegisterRequest.
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password: str):
        """Sets the password of this RegisterRequest.


        :param password: The password of this RegisterRequest.
        :type password: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501
        if password is not None and len(password) < 8:
            raise ValueError("Invalid value for `password`, length must be greater than or equal to `8`")  # noqa: E501

        self._password = password

    @property
    def display_name(self) -> str:
        """Gets the display_name of this RegisterRequest.


        :return: The display_name of this RegisterRequest.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: str):
        """Sets the display_name of this RegisterRequest.


        :param display_name: The display_name of this RegisterRequest.
        :type display_name: str
        """
        if display_name is None:
            raise ValueError("Invalid value for `display_name`, must not be `None`")  # noqa: E501

        self._display_name = display_name
