from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class TokenResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, access_token=None, refresh_token=None, token_type=None, expires_in=None):  # noqa: E501
        """TokenResponse - a model defined in OpenAPI

        :param access_token: The access_token of this TokenResponse.  # noqa: E501
        :type access_token: str
        :param refresh_token: The refresh_token of this TokenResponse.  # noqa: E501
        :type refresh_token: str
        :param token_type: The token_type of this TokenResponse.  # noqa: E501
        :type token_type: str
        :param expires_in: The expires_in of this TokenResponse.  # noqa: E501
        :type expires_in: int
        """
        self.openapi_types = {
            'access_token': str,
            'refresh_token': str,
            'token_type': str,
            'expires_in': int
        }

        self.attribute_map = {
            'access_token': 'access_token',
            'refresh_token': 'refresh_token',
            'token_type': 'token_type',
            'expires_in': 'expires_in'
        }

        self._access_token = access_token
        self._refresh_token = refresh_token
        self._token_type = token_type
        self._expires_in = expires_in

    @classmethod
    def from_dict(cls, dikt) -> 'TokenResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TokenResponse of this TokenResponse.  # noqa: E501
        :rtype: TokenResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def access_token(self) -> str:
        """Gets the access_token of this TokenResponse.

        JWT access token.  # noqa: E501

        :return: The access_token of this TokenResponse.
        :rtype: str
        """
        return self._access_token

    @access_token.setter
    def access_token(self, access_token: str):
        """Sets the access_token of this TokenResponse.

        JWT access token.  # noqa: E501

        :param access_token: The access_token of this TokenResponse.
        :type access_token: str
        """
        if access_token is None:
            raise ValueError("Invalid value for `access_token`, must not be `None`")  # noqa: E501

        self._access_token = access_token

    @property
    def refresh_token(self) -> str:
        """Gets the refresh_token of this TokenResponse.


        :return: The refresh_token of this TokenResponse.
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token: str):
        """Sets the refresh_token of this TokenResponse.


        :param refresh_token: The refresh_token of this TokenResponse.
        :type refresh_token: str
        """

        self._refresh_token = refresh_token

    @property
    def token_type(self) -> str:
        """Gets the token_type of this TokenResponse.


        :return: The token_type of this TokenResponse.
        :rtype: str
        """
        return self._token_type

    @token_type.setter
    def token_type(self, token_type: str):
        """Sets the token_type of this TokenResponse.


        :param token_type: The token_type of this TokenResponse.
        :type token_type: str
        """
        allowed_values = ["Bearer"]  # noqa: E501
        if token_type not in allowed_values:
            raise ValueError(
                "Invalid value for `token_type` ({0}), must be one of {1}"
                .format(token_type, allowed_values)
            )

        self._token_type = token_type

    @property
    def expires_in(self) -> int:
        """Gets the expires_in of this TokenResponse.

        Seconds until access_token expires.  # noqa: E501

        :return: The expires_in of this TokenResponse.
        :rtype: int
        """
        return self._expires_in

    @expires_in.setter
    def expires_in(self, expires_in: int):
        """Sets the expires_in of this TokenResponse.

        Seconds until access_token expires.  # noqa: E501

        :param expires_in: The expires_in of this TokenResponse.
        :type expires_in: int
        """
        if expires_in is None:
            raise ValueError("Invalid value for `expires_in`, must not be `None`")  # noqa: E501

        self._expires_in = expires_in
