from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class UserProfile(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, email=None, display_name=None, created_at=None):  # noqa: E501
        """UserProfile - a model defined in OpenAPI

        :param id: The id of this UserProfile.  # noqa: E501
        :type id: str
        :param email: The email of this UserProfile.  # noqa: E501
        :type email: str
        :param display_name: The display_name of this UserProfile.  # noqa: E501
        :type display_name: str
        :param created_at: The created_at of this UserProfile.  # noqa: E501
        :type created_at: datetime
        """
        self.openapi_types = {
            'id': str,
            'email': str,
            'display_name': str,
            'created_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'email': 'email',
            'display_name': 'display_name',
            'created_at': 'created_at'
        }

        self._id = id
        self._email = email
        self._display_name = display_name
        self._created_at = created_at

    @classmethod
    def from_dict(cls, dikt) -> 'UserProfile':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UserProfile of this UserProfile.  # noqa: E501
        :rtype: UserProfile
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this UserProfile.


        :return: The id of this UserProfile.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this UserProfile.


        :param id: The id of this UserProfile.
        :type id: str
        """

        self._id = id

    @property
    def email(self) -> str:
        """Gets the email of this UserProfile.


        :return: The email of this UserProfile.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this UserProfile.


        :param email: The email of this UserProfile.
        :type email: str
        """

        self._email = email

    @property
    def display_name(self) -> str:
        """Gets the display_name of this UserProfile.


        :return: The display_name of this UserProfile.
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name: str):
        """Sets the display_name of this UserProfile.


        :param display_name: The display_name of this UserProfile.
        :type display_name: str
        """

        self._display_name = display_name

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this UserProfile.


        :return: The created_at of this UserProfile.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this UserProfile.


        :param created_at: The created_at of this UserProfile.
        :type created_at: datetime
        """

        self._created_at = created_at
